# (PART\*) For Each Class {-}

# Class Setup

## Overview of Class Setup

This section will show you how to organize your class to make it easier to administer access to your content. You will need to have a list of who will be taking your class, such as a course roster or sign-up list, as well as a list of additional instructors or teaching assistants. You can make changes later, so the list of students need not be final.

## Identify Funding

### NHGRI STRIDES {#strides-funding}

Through the [STRIDES](https://datascience.nih.gov/strides) program, NHGRI makes funding available to new users of the AnVIL, in collaboration with the [NIH Office of Data Science Strategy](https://datascience.nih.gov/about/odss). NHGRI currently supports the [AnVIL Cloud Credits Program (AC2)](https://anvilproject.org/news/2021/04/12/announcing-anvil-cloud-cost-credits-program) and will have a second round of funding available in fall of 2021.

## Collect Google IDs

AnVIL IDs are based on [Google accounts](account-setup.html#google-account).

Students -- Contact students/participants to get their AnVIL IDs. These should be Gmail addresses or emails with GSuite capabilities. You can link students to [Student Account Setup](student-account-setup.html) for instructions on what they should do.

Co-instructors -- If you will be working with other instructors, such as co-instructors or teaching assistants, you will need to collect their IDs as well.

## Set Up Billing Project

## Set Up Permissions

### Create Groups

<!-- To manage group permissions for Instructors versus students -->

### Add Additional Instructors as "Owner"

<!-- To Instructor Group -->

### Add Students as "Reader"

<!-- to Student Group -->

### Set Permissions

<!-- Set Instructor and Student permissions for Workspace and Terra Billing Projects -->

## Notify Terra

<!-- Request no scheduled maintenance downtime / ask about major changes -->
