# Class Checklist

This checklist can serve as a reminder of the overall suggested steps to make a new class on AnVIL. You might find yourself changing these steps slightly as you become more familiar with AnVIL.

**Billing**

- Obtain funding through the [STRIDES](https://datascience.nih.gov/strides) program (optional)
- Request students make AnVIL IDs (Google IDs) 
- Collect AnVIL IDs (Google IDs) from students
- Create Google Billing Account for your class
- Create Terra Billing Projects for your students
- Deactivate Billing Projects

**Resources**

- Create a Workspace for your class
- Notify Terra of your course dates and times
- Direct students to the Workspace

**Permissions**

- Set up Groups to manage permissions

| AnVIL Group         | Class Workspace | Terra Billing Projects*|
|:--------------------|:----------------|:-----------------------|
| Instructor          | Owner           | Owner                  |
| Teaching assistants | Writer          | Owner                  |
| Students            | Reader          | User                   |

\* You should have n + 1 Terra Billing Projects: one for each student and one shared by instructors.
